add_newline = false
format = "$hostname$directory$character"

[directory]
home_symbol = ""
style = "bold #7aa2f7"
truncation_length = 2
truncation_symbol = "…/"
format = "[$path]($style)"

[hostname]
ssh_only = true
format = "[$hostname](bold yellow) "

[character]
success_symbol = "[/](bold #7aa2f7)"
error_symbol = "[/](bold #7aa2f7)"
