os:
  edit: '/home/hijack/.config/lazygit/open_changed_in_nvim.sh "{{filename}}" "{{line}}"'
  editAtLine: '/home/hijack/.config/lazygit/open_changed_in_nvim.sh "{{filename}}" "{{line}}"'
gui:
  showNumstatInFilesView: true
git:
  ignoreWhitespaceInDiffView: true
  diffContextSize: 5
  pagers:
    - pager: '/home/hijack/.config/lazygit/diff-pager.sh'
